network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.0.231/16
        - 2001:1b70:82a1:103::e7/64
      nameservers:
        search:
          - vts.com
          - athtem.eei.ericsson.se
        addresses:
          - 192.168.0.1
      routes:
        - to: default
          via: 192.168.0.1
        - to: default
          via: 2001:1b70:82a1:103::1
