network:
  version: 2
  ethernets:
    ens3:
      addresses:
        - 192.168.0.197/16
        - 2001:1b70:82a1:103::c5/64
      routes:
        - to: default
          via: 192.168.0.1
        - to: default
          via: 2001:1b70:82a1:103::1
